### ISSUE TITLE
启用主题出问题

### ISSUE THREAD

**Issue by Qiup7664** [liaocp666/Jasmine#16]
你好，我在启用主题后，首页出现乱码
![image](https://github.com/liaocp666/Jasmine/assets/56213419/5e04a2f3-fbb2-4f33-b2cf-39eb11279e56)

**Comment by liaocp666** [comment]
这个问题在最新版本修复了。如果你不来下载最新版本，可以在后台设置一下中间菜单和左侧菜单就可 @Qiup7664
