### ISSUE TITLE
现在的缩略图比例不对是会拉伸的，不妨裁剪一下

### ISSUE THREAD

**Issue by rainlogs** [liaocp666/Jasmine#2]

**Comment by rainlogs** [comment]
> 缩略图是个问题，我没有找到合适的裁剪库，你知道有那个php的库适合 tp 来动态生成裁剪后的图片吗？ @rainlogs

不知道诶。不过之前给图片加了个object-fit: cover的css，也能裁。
感觉足够了，图片内容缺一点比拉伸还是要顺眼些。

**Comment by liaocp666** [comment]
感谢告知，已修改

**Comment by liaocp666** [comment]
> > 缩略图是个问题，我没有找到合适的裁剪库，你知道有那个php的库适合 tp 来动态生成裁剪后的图片吗？ @rainlogs
> 
> 不知道诶。不过之前给图片加了个object-fit: cover的css，也能裁。 感觉足够了，图片内容缺一点比拉伸还是要顺眼些。

感谢告知，已修改
