### ISSUE TITLE
感觉之前下滑页面更好？

### ISSUE THREAD

**Issue by StarsRivers** [liaocp666/Jasmine#21]
问题描述：之前进行页面下滑的时候顶栏是高斯模糊的效果，现在直接变成改透明度了
出现版本：v2.4.0+

**Comment by liaocp666** [comment]
你有兴趣实现一下吗？

**Comment by liaocp666** [comment]
#19

**Comment by liaocp666** [comment]
commit [78a77be](https://github.com/liaocp666/Jasmine/commit/78a77be99a061942659bf62d34afce8101efd8ae)

**Comment by liaocp666** [comment]
78a77be99a061942659bf62d34afce8101efd8ae
