### ISSUE TITLE
怎么设置默认是light模式

### ISSUE THREAD

**Issue by danaoairuike** [liaocp666/Jasmine#23]
用不同的浏览器，每次打开都是默认深色，能否有默认深色和浅色模式的选择？谢谢

**Comment by danaoairuike** [comment]
但我每次打开默认竟然是dark

**Comment by liaocp666** [comment]
厚黑是配色，不会更改深色模式。

如果是false，那代码不就走 remove("dark") 了，移除了深色模式，那不默认就是浅色模式？

**Comment by liaocp666** [comment]
发个网址我看看

**Comment by danaoairuike** [comment]
news.baodian.co

**Comment by danaoairuike** [comment]
我觉得还有一个可能就是cache，现在用不同的手机测了好几次，都是浅色

如果您打开了也是浅色，就关闭这个issue吧

谢谢

**Comment by liaocp666** [comment]
> 我觉得还有一个可能就是cache，现在用不同的手机测了好几次，都是浅色
> 
> 如果您打开了也是浅色，就关闭这个issue吧
> 
> 谢谢

打开是浅色的
