### ISSUE TITLE
第一个分类无法正常显示

### ISSUE THREAD

**Issue by 1229984599** [liaocp666/Jasmine#24]
主题版本： 2.5.2
在第一个分类中的文章会直接显示文章里所有内容，第二个分类就一点问题也没有
![image](https://github.com/liaocp666/Jasmine/assets/34052312/37bf1dc0-5696-43db-bbe3-095d306d1d11)
### 以下是我分类设置信息：
![image](https://github.com/liaocp666/Jasmine/assets/34052312/df0e8c3b-ff1f-401b-a1f5-4e60226cb7f0)
还请作者大大空了看看

**Comment by liaocp666** [comment]
方便发个网址吗？你这个问题还是头一个，之前没人反馈有这个问题

**Comment by 1229984599** [comment]
> 方便发个网址吗？你这个问题还是头一个，之前没人反馈有这个问题

https://blog.moxiaoying.top/，感谢大佬😄
