### ISSUE TITLE
手机屏幕上，post tag的css有bug；并且附上了解决方案

### ISSUE THREAD

**Issue by danaoairuike** [liaocp666/Jasmine#25]
## 这个截图是有问题的时候：

![image](https://github.com/liaocp666/Jasmine/assets/129480823/c680c212-a92d-47e2-a36d-250c1475860c)
![image](https://github.com/liaocp666/Jasmine/assets/129480823/508fed31-def1-4833-8d03-d66d79f45c9c)

## 下面是解决方案：
https://github.com/liaocp666/Jasmine/blob/b26543f2b3e5804ecf0171e94f86158a1848371c/post.php#L18

这一行，加上 `flex-wrap  gap-y-2`这2个class 就可以了

**Comment by liaocp666** [comment]
感谢，你可以尝试下提个 pr 过来

**Comment by danaoairuike** [comment]
> 感谢，你可以尝试下提个 pr 过来

客气了
应该感谢你

你下次更新代码的时候修一下吧，我就不用提PR了
