### ISSUE TITLE
Bug: 当分类下面没有文章的时候，右侧的博客主人的用户名消失了

### ISSUE THREAD

**Issue by danaoairuike** [liaocp666/Jasmine#26]
请看视频

点击上面的几个分类的时候，只有一个分类下面有文章，其他的分类都暂时没有文章，点击他们，竟然导致右侧博客主人的用户名消失

辛苦啦

https://github.com/liaocp666/Jasmine/assets/129480823/e3526ef2-1a6a-4ca2-8a1c-bf1aafee002e

**Comment by liaocp666** [comment]
那个是文章作者。没文章自然自然就没作者

**Comment by danaoairuike** [comment]
但是，这是个人博客，难不成这个博客还有多个作者？

**Comment by liaocp666** [comment]
> 但是，这是个人博客，难不成这个博客还有多个作者？
> 
> 就算是没有文章就没有作者，但有作者介绍哦
> 
> @liaocp666

我要是没记错的话，可以新增用户吧。新增的用户发的文章，难道也要显示第一个人的？

**Comment by danaoairuike** [comment]
> > 但是，这是个人博客，难不成这个博客还有多个作者？
> > 就算是没有文章就没有作者，但有作者介绍哦
> > @liaocp666
> 
> 我要是没记错的话，可以新增用户吧。新增的用户发的文章，难道也要显示第一个人的？

是，可以添加其他用户。但，最常见的用例是博客作者自己一个人用，很少会遇到两个人自己共用一个博客

这里没办法简单覆盖到其他用户的情况，
所以只能解决一个多数人都会遇到的问题：分类下如果没有文章，导致用户名没显示出来。
更何况，作者简介是永远显示的，这其实已经说明问题了。

### 所以我建议如下：

把这个文件里的第12和15行改一下：
https://github.com/liaocp666/Jasmine/blob/main/component/sidebar.php

从`$this->author->screenName()` 改为 `$this->user->screenName();`即可

**Comment by danaoairuike** [comment]
但我个人的建议是， 如果您有空，还是修一下，毕竟这是个问题，尤其是很多人只是自己在用博客，很少存在和别人共用的情况

辛苦了
