### ISSUE TITLE
启用主题后，白屏

### ISSUE THREAD

**Issue by liesauer** [liaocp666/Jasmine#27]
我博客是1.1版本的，博客主页也是白屏，日志开启E_ALL也没有任何报错。

![image](https://github.com/liaocp666/Jasmine/assets/8676741/e3500cf3-d46c-44dd-88e3-66719ab2928d)

**Comment by liaocp666** [comment]
https://github.com/liaocp666/Jasmine/wiki/%E4%B8%BB%E9%A2%98%E5%AE%89%E8%A3%85#%E7%8E%AF%E5%A2%83

**Comment by liesauer** [comment]
经验证确实不支持1.1版本，已升级至最新的1.2.1，现在可以出来了。
