### ISSUE TITLE
白天模式、夜间模式切换，网页内容会上下跳动

### ISSUE THREAD

**Issue by liesauer** [liaocp666/Jasmine#29]
为了减小大小，录屏只录了一小部分，整个网页包括正文，侧边栏都是会跳动的

https://github.com/liaocp666/Jasmine/assets/8676741/822581ac-ef58-496d-82fd-d58fa55775b7

**Comment by liaocp666** [comment]
无法重新，你换个浏览器

**Comment by liesauer** [comment]
找到问题了，是和MD插件冲突了，MD插件接管了前端的渲染，默认下其实生效了MD插件的样式，切到暗色模式后，生效的是主题的样式，部分字号不一样就导致了内容一上一下跳动。
