### ISSUE TITLE
期待加入Ajax/instantclick的适配

### ISSUE THREAD

**Issue by HhhowardWang** [liaocp666/Jasmine#34]
如题，如果能加入的话就更棒了！

我自己尝试加了instantclick，但因为不太理解原理所以配置不好，点击sidebar和sidebar-left区域时还是会刷新，其他位置的链接没有问题。期待能在发布版本里自带支持！

---

我没看出来目前主题是不是已经支持了，我感觉还没有，是因为有的需要无刷新的插件直接添加后不生效，但自己引入instantclick后有效果了。

**Comment by liaocp666** [comment]
1.x 版本有局部刷新功能，2.x 去掉了，就是因为加入了之后有各种问题需要兼容，所以就去掉了

**Comment by HhhowardWang** [comment]
> 1.x 版本有局部刷新功能，2.x 去掉了，就是因为加入了之后有各种问题需要兼容，所以就去掉了。后续不打算引入此功能

好吧，谢谢啦
