### ISSUE TITLE
切换成这个主题后报错了

### ISSUE THREAD

**Issue by iampcfox** [liaocp666/Jasmine#36]
Fatal error: Class 'Widget\Metas\Category\Rows' not found in /www/wwwroot/blog.fxpixels.site/usr/themes/jasmine/core/meta.php on line 9

然后连后台修改外观都改不了，只能从数据库改

是不是对typecho有版本要求？我的版本是 1.1 (17.10.30)

**Comment by liaocp666** [comment]
https://github.com/liaocp666/Jasmine/wiki/%E4%B8%BB%E9%A2%98%E5%AE%89%E8%A3%85#%E7%8E%AF%E5%A2%83
