### ISSUE TITLE
自定义脚本能否改成自己添加<script></script>，而不是强制？

### ISSUE THREAD

**Issue by i5ea** [liaocp666/Jasmine#39]
<script>
    <?php $this->options->customScript(); ?>
</script>

我觉得去掉默认的<script></script>会更合理一些

一般的统计代码都是完整的包含了script标签的

**Comment by liaocp666** [comment]
去掉默认的script标签，用户也许就会填一些其他内容进去，导致在页面显示。目前也不好去除，因为有很多用户使用了这块内容，如果主题去掉，这块内容就直接暴露在页面了
