### ISSUE TITLE
数学公式显示问题

### ISSUE THREAD

**Issue by glerium** [liaocp666/Jasmine#41]
Jasmine主题和[MathJax](https://github.com/yuzhongzhibi/typecho_mathjax_plugin)插件搭配使用时，会导致所有的数学公式强制换行（如下图）。在Typecho原生主题上使用MathJax则不会出现这个问题。请问有解决办法吗？
![image](https://github.com/liaocp666/Jasmine/assets/36121687/36bf61fe-d701-44ff-a716-e95ec14e9aa3)

**Comment by liaocp666** [comment]
有网址看看吗？ @glerium

**Comment by glerium** [comment]
文章地址在这里： https://879076.xyz/index.php/archives/14/



---原始邮件---
发件人: "Kent ***@***.***&gt;
发送时间: 2023年10月19日(周四) 上午9:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liaocp666/Jasmine] 数学公式显示问题 (Issue #41)




 
有网址看看吗？ @glerium

**Comment by glerium** [comment]
问题已经解决了，我参考https://github.com/litten/hexo-theme-yilia/blob/master/layout/_partial/mathjax.ejs 魔改了一下MathJax插件发现没问题了。感谢作者关注！
