### ISSUE TITLE
国内启用主题后，报错Server Error，网页标题显示500

### ISSUE THREAD

**Issue by mikenable2199** [liaocp666/Jasmine#48]
1.下载主题解压，文件夹上传至主题目录下；
2.管理界面启用主题；
3.打开网页提示以上错误；
4.切换为其他主体后，网站显示正常；

**Comment by liaocp666** [comment]
https://github.com/liaocp666/Jasmine/wiki/%E4%B8%BB%E9%A2%98%E5%AE%89%E8%A3%85#%E7%8E%AF%E5%A2%83

你的环境是否符合要求？

**Comment by bytetopia** [comment]
遇到了同样的问题，mysql 8.3, php 7.4 typecho 1.3，typecho装在docker里，想请问下有什么办法可以查看详细的error原因吗

**Comment by bytetopia** [comment]
update: 回退到typecho 1.2.1解决，1.3下面“中间头部菜单”等功能也不能正常使用，可能是typecho修改了api。不要用typecho nightly docker 镜像就行了😂
