### ISSUE TITLE
关于页面头像

### ISSUE THREAD

**Issue by anyiweb** [liaocp666/Jasmine#5]
首页的头像显示是正常的
![image](https://user-images.githubusercontent.com/60560420/230031916-f0b8acbc-3514-4802-b633-cb2c328d3bf2.png)
但是“关于页面”的头像是灰色的
![image](https://user-images.githubusercontent.com/60560420/230032729-9a3eb7b9-6d21-445f-83c6-b7736654d4fa.png)
链接变成了这样
![image](https://user-images.githubusercontent.com/60560420/230032836-7a03db1c-30fa-4bd0-8774-94c15785f667.png)

**Comment by liaocp666** [comment]
关于页面头像，是根据关于页面作者生成的。你关于页面和首页作者不是同一个
