### ISSUE TITLE
标签不按预期工作

### ISSUE THREAD

**Issue by cuixiping** [liaocp666/Jasmine#50]
Typecho后台管理中的专门的Tag管理没用上, 发文章时不能选前面已经设好的Tag, 要手动填, 但手动填的又不能设slug

**Comment by liaocp666** [comment]
没懂你的意思，建议你带上图片，进一步详细说明下

**Comment by cuixiping** [comment]
重新做了一遍, 没有复现了, 可能之前是我哪里弄错了

**Comment by cuixiping** [comment]
我搞明白了, 这个问题不是主题的问题, 是typecho的问题.
重新描述一下:

1. 标签是中文,但slug是英文, 比如标签 "个人", slug设为"personal"
2. 编写文章时, 标签栏输入"个"或"per" , 都不会把"个人"或"personal"提示出来.
