### ISSUE TITLE
装了Fancybox之后，点开图片，下方的页面会整体右移

### ISSUE THREAD

**Issue by majw88** [liaocp666/Jasmine#52]
装了Fancybox之后，文章页面点击图片出浮层之后，下方的页面会整体右移一大截，关掉图片浮层，页面会再移动回来。

**换其他主题则无这个问题。**不知道该怎么解决？

**Comment by liaocp666** [comment]
你可以试试 https://github.com/Tokinx/ViewImage 灯箱
