### ISSUE TITLE
typecho更新了1.3.0，主题有计划更新吗，升级之后报500错误

### ISSUE THREAD

**Issue by cnkids** [liaocp666/Jasmine#56]
开了debug模式，提示错误信息

Cannot assign null to property Typecho\Widget::$stack of type array
TypeError: Cannot assign null to property Typecho\Widget::$stack of type array in /usr/themes/jasmine/core/meta.php:23
Stack trace:
#0 var/Typecho/Widget.php(155): Jasmine_Meta_Row->execute()
#1 usr/themes/jasmine/component/menu.php(14): Typecho\Widget::widget()
#2 var/Widget/Archive.php(1263): require('...')
#3 usr/themes/jasmine/index.php(22): Widget\Archive->need()
#4 var/Widget/Archive.php(1345): require_once('...')
#5 var/Typecho/Router.php(88): Widget\Archive->render()
#6 /index.php(23): Typecho\Router::dispatch()
#7 {main}

**Comment by liaocp666** [comment]
等 typecho 正式发布1.3.0，再更新主题

**Comment by liaocp666** [comment]
后续会修复，你也可以尝试修复

**Comment by cnkids** [comment]
OK，那我有时间看看
